name: Update Card Renders

on:
  # push: 
  #   paths:
  #     - 'templates/**'
  #     - 'card-data/cards.csv'

  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
          
      - name: Install necessary fonts
        run: |
          ./scripts/install-fonts.sh

      - name: Initialize npm project
        run: npm init -y
        
      - name: Create export folders
        run: |
          mkdir -p export
          mkdir -p tabletop

      - name: Render cards
        run: node scripts/create-cards.mjs

      - name: Commit Changes and Push
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git add ./export/*
          git add ./tabletop/*
          git commit -m "Rendered cards. [skip ci]"
          git push
