name: Provision Infrastructure

on:
  workflow_dispatch:
  workflow_call:
      
env:
  TF_VAR_do_token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
  SPACES_ACCESS_KEY_ID: ${{ secrets.SPACES_ACCESS_KEY_ID }}
  SPACES_SECRET_ACCESS_KEY: ${{ secrets.SPACES_SECRET_ACCESS_KEY }}
  
jobs:
  provision-infrastructure:
    runs-on: ubuntu-latest
    
    steps:
    - name: Install OpenTofu
      uses: opentofu/setup-opentofu@v1
      
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Apply env variables
      run: . apply-env.sh .env
    
    - name: Initialize OpenTofu
      run: tofu init
      working-directory: ./opentofu
        
    - name: Plan provision
      run: tofu plan -no-color
      
    - name: Apply provision
      run: tofu apply -auto-approve