name: Validate Cards

on:
  workflow_dispatch:
  workflow_call:

jobs:
  validate-cards:
    runs-on: ubuntu-latest

    steps:
    - name: Use NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        check-latest: true
    
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Install Node dependencies
      run: npm install
    
    - name: Validate Cards
      run: node --env-file=.env ./scripts/validate-cards.mjs